export { MypageHomePage } from './home/page'
export { MypageInquiriesPage } from './inquiries/page'
export { MypageInstructorApplyPage } from './instructor-apply/page'
export { MypageInstructorApplyConsentPage } from './instructor-apply/consent/page'
export { MypageSettingsPage } from './settings/page'
