export { TrainedTeachersRegistrationBasicInfoParagraph } from './paragraphs/basic-info-paragraph'
export { TrainedTeachersRegistrationBusinessKpiParagraph } from './paragraphs/business-kpi-paragraph'
export { TrainedTeachersRegistrationTypeSettingsParagraph } from './paragraphs/type-settings-paragraph'
export { TrainedTeachersRegistrationEducationCurriculumParagraph } from './paragraphs/education-curriculum-paragraph'
export { TrainedTeachersRegistrationEducationScheduleSettingsParagraph } from './paragraphs/education-schedule-settings-paragraph'
