/**
 * 실적 관리 > 합계 탭 시안용 목업 수치 (레거시·테스트 참고용)
 * - 런타임 합계 탭은 remote `GET /api/admin/performance/summary` 또는
 *   목록 행 클라이언트 집계(`buildSummaryTabViewFromRows`)를 사용한다.
 */

import type {
  SummaryCategoryKey,
  SummaryRow,
  SummarySubRowKey,
} from './education-record-types'

const emptyRow: SummaryRow = {
  schoolCount: 0,
  classCount: 0,
  participants: 0,
  educationHours: 0,
  generalVolunteers: 0,
  staffVolunteers: 0,
  generalTeachers: 0,
  educatedTeachers: 0,
  instructors: 0,
}

/** 카테고리 → 서브행 → 수치 */
export const SUMMARY_MOCK: Record<
  SummaryCategoryKey,
  Partial<Record<SummarySubRowKey, SummaryRow>>
> = {
  economyFinance: {
    elementary: {
      schoolCount: 619,
      classCount: 619,
      participants: 44534,
      educationHours: 1784,
      generalVolunteers: 942,
      staffVolunteers: 119,
      generalTeachers: 630,
      educatedTeachers: 4,
      instructors: 519,
    },
    middle: {
      schoolCount: 59,
      classCount: 59,
      participants: 19725,
      educationHours: 210,
      generalVolunteers: 15,
      staffVolunteers: 259,
      generalTeachers: 152,
      educatedTeachers: 0,
      instructors: 121,
    },
    high: {
      schoolCount: 143,
      classCount: 186,
      participants: 8067,
      educationHours: 627,
      generalVolunteers: 71,
      staffVolunteers: 259,
      generalTeachers: 152,
      educatedTeachers: 0,
      instructors: 121,
    },
    adult: {
      schoolCount: 8,
      classCount: 133,
      participants: 7281,
      educationHours: 1360,
      generalVolunteers: 0,
      staffVolunteers: 25,
      generalTeachers: 1,
      educatedTeachers: 0,
      instructors: 187,
    },
    total: {
      schoolCount: 831,
      classCount: 1017,
      participants: 81140,
      educationHours: 4012,
      generalVolunteers: 1030,
      staffVolunteers: 559,
      generalTeachers: 839,
      educatedTeachers: 8,
      instructors: 923,
    },
  },
  careerEmployment: {
    elementary: {
      schoolCount: 412,
      classCount: 418,
      participants: 28140,
      educationHours: 1124,
      generalVolunteers: 512,
      staffVolunteers: 96,
      generalTeachers: 402,
      educatedTeachers: 2,
      instructors: 318,
    },
    middle: {
      schoolCount: 71,
      classCount: 89,
      participants: 12210,
      educationHours: 324,
      generalVolunteers: 23,
      staffVolunteers: 188,
      generalTeachers: 121,
      educatedTeachers: 0,
      instructors: 102,
    },
    high: {
      schoolCount: 112,
      classCount: 163,
      participants: 6431,
      educationHours: 520,
      generalVolunteers: 55,
      staffVolunteers: 201,
      generalTeachers: 131,
      educatedTeachers: 0,
      instructors: 98,
    },
    adult: {
      schoolCount: 12,
      classCount: 98,
      participants: 5123,
      educationHours: 980,
      generalVolunteers: 2,
      staffVolunteers: 18,
      generalTeachers: 1,
      educatedTeachers: 0,
      instructors: 142,
    },
    total: {
      schoolCount: 607,
      classCount: 768,
      participants: 51904,
      educationHours: 2948,
      generalVolunteers: 592,
      staffVolunteers: 503,
      generalTeachers: 655,
      educatedTeachers: 2,
      instructors: 660,
    },
  },
  entrepreneurship: {
    elementary: {
      schoolCount: 356,
      classCount: 360,
      participants: 22410,
      educationHours: 912,
      generalVolunteers: 410,
      staffVolunteers: 78,
      generalTeachers: 330,
      educatedTeachers: 1,
      instructors: 290,
    },
    middle: {
      schoolCount: 48,
      classCount: 52,
      participants: 9840,
      educationHours: 172,
      generalVolunteers: 10,
      staffVolunteers: 160,
      generalTeachers: 110,
      educatedTeachers: 0,
      instructors: 88,
    },
    high: {
      schoolCount: 98,
      classCount: 142,
      participants: 5218,
      educationHours: 431,
      generalVolunteers: 48,
      staffVolunteers: 188,
      generalTeachers: 121,
      educatedTeachers: 0,
      instructors: 82,
    },
    adult: {
      schoolCount: 6,
      classCount: 82,
      participants: 4112,
      educationHours: 720,
      generalVolunteers: 0,
      staffVolunteers: 12,
      generalTeachers: 1,
      educatedTeachers: 0,
      instructors: 118,
    },
    total: {
      schoolCount: 508,
      classCount: 636,
      participants: 41580,
      educationHours: 2235,
      generalVolunteers: 468,
      staffVolunteers: 438,
      generalTeachers: 562,
      educatedTeachers: 1,
      instructors: 578,
    },
  },
  digitalLiteracy: {
    high: {
      schoolCount: 141,
      classCount: 180,
      participants: 7220,
      educationHours: 552,
      generalVolunteers: 71,
      staffVolunteers: 250,
      generalTeachers: 132,
      educatedTeachers: 0,
      instructors: 110,
    },
    university: {
      schoolCount: 24,
      classCount: 78,
      participants: 4120,
      educationHours: 380,
      generalVolunteers: 8,
      staffVolunteers: 96,
      generalTeachers: 24,
      educatedTeachers: 0,
      instructors: 88,
    },
    adult: {
      schoolCount: 5,
      classCount: 66,
      participants: 3210,
      educationHours: 612,
      generalVolunteers: 0,
      staffVolunteers: 12,
      generalTeachers: 1,
      educatedTeachers: 0,
      instructors: 92,
    },
    total: {
      schoolCount: 170,
      classCount: 324,
      participants: 14550,
      educationHours: 1544,
      generalVolunteers: 79,
      staffVolunteers: 358,
      generalTeachers: 157,
      educatedTeachers: 0,
      instructors: 290,
    },
  },
}

/** 최하단 "전체 합계" 1행 — 4개 카테고리 total 합산 (시안 수치 기준) */
export const SUMMARY_GRAND_TOTAL: SummaryRow = {
  schoolCount: 2116,
  classCount: 2745,
  participants: 189174,
  educationHours: 10739,
  generalVolunteers: 2169,
  staffVolunteers: 1858,
  generalTeachers: 2213,
  educatedTeachers: 11,
  instructors: 2451,
}

/** 특정 카테고리·서브행이 데이터가 없을 때 fallback 용 0 채움 */
export const SUMMARY_EMPTY_ROW = emptyRow
