export type { ProgramParticipantApplicationEditorVariant } from '@jakorea/form-schema/template-registry'
export {
  isTitleWithPeriodParagraph,
  normalizeTitleWithPeriodParagraph,
  resolveTitleEndPeriodMode,
  resolveTitleStartPeriodMode,
  titlePeriodEndDisplayText,
  titlePeriodStartDisplayText,
  LECTURE_REPORT_START_ACTIVITY_PRESET_LABEL,
  LECTURE_REPORT_END_ACTIVITY_PRESET_LABEL,
  resolveLectureReportStartPeriodChoice,
  resolveLectureReportEndPeriodChoice,
  resolveLectureReportActivityDaySample,
  lectureReportStartActivityPreviewLabel,
  lectureReportEndActivityPreviewLabel,
  type LectureReportStartPeriodChoice,
  type LectureReportEndPeriodChoice,
  UJAT_EDU_JOURNAL_START_ACTIVITY_PRESET_LABEL,
  UJAT_EDU_JOURNAL_END_ACTIVITY_PRESET_LABEL,
  UJAT_EDU_JOURNAL_END_NO_DEADLINE_PREVIEW_LABEL,
  resolveUjatEduJournalStartPeriodChoice,
  resolveUjatEduJournalEndPeriodChoice,
  resolveUjatEduJournalActivityDaySample,
  ujatEduJournalStartImmediatePreviewLabel,
  ujatEduJournalStartActivityPreviewLabel,
  ujatEduJournalEndActivityPreviewLabel,
  type UjatEduJournalStartPeriodChoice,
  type UjatEduJournalEndPeriodChoice,
  UJAT_EDU_PLAN_END_ACTIVITY_PRESET_LABEL,
  UJAT_EDU_PLAN_END_NO_DEADLINE_PREVIEW_LABEL,
  resolveUjatEduPlanStartPeriodChoice,
  resolveUjatEduPlanEndPeriodChoice,
  resolveUjatEduPlanActivityDaySample,
  ujatEduPlanStartImmediatePreviewLabel,
  ujatEduPlanEndActivityPreviewLabel,
  type UjatEduPlanStartPeriodChoice,
  type UjatEduPlanEndPeriodChoice,
} from '@jakorea/form-schema/writing-form'
