/** 교육 진행 일정 열 고정 폭 */
export const PARTICIPATING_INSTITUTIONS_SESSIONS_COLUMN_WIDTH = 360

/** 교재 배송 현황 테이블 열 폭 (StatusDropdownCell 배지 폭과 별도) */
export const PARTICIPATING_INSTITUTIONS_TEXTBOOK_STATUS_COLUMN_WIDTH = 152

/** 교재 배송 현황 StatusDropdownCell 배지·트리거·드롭다운 패널 폭 */
export const PARTICIPATING_INSTITUTIONS_TEXTBOOK_STATUS_DROPDOWN_BADGE_WIDTH = 120

/** StatusDropdownCell `style` — 배지 100×32 (tag100 레이아웃과 병행) */
export const PARTICIPATING_INSTITUTIONS_TEXTBOOK_STATUS_DROPDOWN_STYLE = {
  width: PARTICIPATING_INSTITUTIONS_TEXTBOOK_STATUS_DROPDOWN_BADGE_WIDTH,
  minWidth: PARTICIPATING_INSTITUTIONS_TEXTBOOK_STATUS_DROPDOWN_BADGE_WIDTH,
  maxWidth: PARTICIPATING_INSTITUTIONS_TEXTBOOK_STATUS_DROPDOWN_BADGE_WIDTH,
  height: 32,
  minHeight: 32,
  maxHeight: 32,
} as const

/** 교육 학급 수 열 폭 (헤더 잘림 방지) */
export const PARTICIPATING_INSTITUTIONS_CLASS_COUNT_COLUMN_WIDTH = 112

/** 배정 강사 열 폭 */
export const PARTICIPATING_INSTITUTIONS_ASSIGNED_INSTRUCTOR_COLUMN_WIDTH = 140

/** 참여 기관 목록 테이블 최소 가로 스크롤 폭(열 width 합) */
export const PARTICIPATING_INSTITUTIONS_TABLE_MIN_SCROLL_X =
  80 +
  180 +
  200 +
  PARTICIPATING_INSTITUTIONS_SESSIONS_COLUMN_WIDTH +
  PARTICIPATING_INSTITUTIONS_TEXTBOOK_STATUS_COLUMN_WIDTH +
  96 +
  PARTICIPATING_INSTITUTIONS_CLASS_COUNT_COLUMN_WIDTH +
  100 +
  120 +
  PARTICIPATING_INSTITUTIONS_ASSIGNED_INSTRUCTOR_COLUMN_WIDTH
