/** 교육 진행 일정 열 고정 폭 */
export const PARTICIPATING_INSTITUTIONS_SESSIONS_COLUMN_WIDTH = 360

/** 교재 배송 현황 테이블 열 폭 (StatusDropdownCell 배지 폭과 별도) */
export const PARTICIPATING_INSTITUTIONS_TEXTBOOK_STATUS_COLUMN_WIDTH = 136

/** 교재 배송 현황 StatusDropdownCell 배지·트리거·드롭다운 패널 폭 */
export const PARTICIPATING_INSTITUTIONS_TEXTBOOK_STATUS_DROPDOWN_BADGE_WIDTH = 100

/** StatusDropdownCell `style` — 배지 100×30, 패널은 공통 CSS에서 배지+16px */
export const PARTICIPATING_INSTITUTIONS_TEXTBOOK_STATUS_DROPDOWN_STYLE = {
  width: PARTICIPATING_INSTITUTIONS_TEXTBOOK_STATUS_DROPDOWN_BADGE_WIDTH,
  minWidth: PARTICIPATING_INSTITUTIONS_TEXTBOOK_STATUS_DROPDOWN_BADGE_WIDTH,
  maxWidth: PARTICIPATING_INSTITUTIONS_TEXTBOOK_STATUS_DROPDOWN_BADGE_WIDTH,
  height: 30,
  minHeight: 30,
  maxHeight: 30,
} as const

/** 참여 기관 목록 테이블 최소 가로 스크롤 폭(열 width 합) */
export const PARTICIPATING_INSTITUTIONS_TABLE_MIN_SCROLL_X =
  80 +
  180 +
  200 +
  PARTICIPATING_INSTITUTIONS_SESSIONS_COLUMN_WIDTH +
  PARTICIPATING_INSTITUTIONS_TEXTBOOK_STATUS_COLUMN_WIDTH +
  96 +
  100 +
  100 +
  120
