export type ProgramParticipantApplicationEditorVariant =
  | 'individual'
  | 'institution'
  | 'economy-application-institution'
  | 'trained-teachers-application-institution'
  | 'gemini-application-institution'
  | 'gemini-application-instructor'
  | 'ujat-application-institution'
  | 'ujat-application-volunteer'
  | 'applicant-recruit-institution'
  | 'ujat-recruit-institution'
  | 'applicant-recruit-individual'
  | 'recruit-instructor'
  | 'recruit-volunteer'
  | 'ujat-recruit-volunteer'
  | 'instructor'
  | 'volunteer'
